name: a2c
method: grid
metric:
  name: outer/hypervolume
  goal: maximize
parameters:
  seed:
    values: [ 0, 1, 2, 3, 4 ]
  oracle:
    lr_actor:
      values: [ 0.0007, 0.0005, 0.0003, 0.0001 ]
    lr_critic:
      values: [ 0.0007, 0.0005, 0.0003, 0.0001 ]
    num_hidden_layers:
      values: [ 1 ]
    hidden_size:
      values: [ 256 ]
    max_grad_norm:
      values: [ -1, 0.5 ]
    pretraining_steps:
      values: [ 10000 ]
    online_steps:
      values: [ 10000 ]