name: dqn
method: grid
metric:
  name: outer/hypervolume
  goal: maximize
parameters:
  seeds:
    values: [ 0, 1, 2, 3, 4 ]
  oracle:
    lr:
      values: [ 0.0005, 0.00045, 0.0004, 0.00035, 0.0003, 0.0002 ]
    num_hidden_layers:
      values: [ 2 ]
    num_referents:
      values: [ 16, 32 ]
    hidden_size:
      values: [ 256 ]
    pretraining_steps:
      values: [ 10000, 15000 ]
    online_steps:
      values: [ 10000 ]