name: dqn
method: grid
metric:
  name: outer/hypervolume
  goal: maximize
parameters:
  seed:
    values: [ 0, 1, 2, 3, 4 ]
  oracle:
    lr:
      values: [ 0.0007, 0.0005, 0.0004, 0.0003 ]
    num_hidden_layers:
      values: [ 2, 3 ]
    hidden_size:
      values: [ 256 ]
    activation:
      values: [ tanh ]
    pre_train_freq:
      values: [ 1, 4, 8 ]
    num_referents:
      values: [ 16, 32 ]
    batch_size:
      values: [ 32, 64, 128 ]
    buffer_size:
      values: [ 2500, 5000, 7500, 10000 ]
    pretraining_steps:
      values: [ 5000, 10000 ]
    online_steps:
      values: [ 5000, 10000 ]