name: a2c_no_pretrain_7
method: bayes
metric:
  name: mean_hv
  goal: maximize
parameters:
  num_seeds:
    values: [ 5 ]
  oracle:
    aug:
      values: [ 0.1, 0.2, 0.3 ]
    scale:
      values: [ 50, 100, 150 ]
    lr_actor:
      distribution: q_uniform
      min: 0.0001
      max: 0.0005
      q: 0.0001
    lr_critic:
      distribution: q_uniform
      min: 0.0005
      max: 0.001
      q: 0.0001
    hidden_size_actor:
      values: [ 64, 128, 256 ]
    hidden_size_critic:
      values: [ 64, 128, 256 ]
    num_hidden_layers_actor:
      values: [ 2, 3 ]
    num_hidden_layers_critic:
      values: [ 2, 3 ]
    max_grad_norm:
      values: [ 1, 5, 10, 50 ]
    v_coef:
      values: [ 0.3, 0.4, 0.5 ]
    e_coef:
      distribution: q_uniform
      min: 0.01
      max: 0.05
      q: 0.01
    n_steps:
      values: [ 10, 16, 20 ]
    normalize_advantage:
      values: [ false ]
    pretraining_steps:
      values: [ 0 ]
    online_steps:
      values: [ 3e4 ]