name: a2c_7
method: grid
metric:
  name: outer/hypervolume
  goal: maximize
parameters:
  seed:
    values: [ 0, 1, 2, 3, 4 ]
  oracle:
    lr_actor:
      values: [ 0.0002, 0.00025, 0.0003, 0.00035 ]
    lr_critic:
      values: [ 0.00055, 0.0006, 0.00065, 0.0007]
    num_hidden_layers:
      values: [ 2, 3 ]
    hidden_size:
      values: [ 64 ]
    num_referents:
      values: [ 16 ]
    max_grad_norm:
      values: [ 0.5, 1, 2 ]
    v_coef:
      values: [ 0.5 ]
    e_coef:
      values: [ 0.01 ]
    normalize_advantage:
      values: [ false ]
    critic_activation:
      values: [ tanh ]
    actor_activation:
      values: [ tanh ]
    online_steps:
      values: [ 50000 ]