name: a2c_no_pretrain_5
method: grid
metric:
  name: outer/hypervolume
  goal: maximize
parameters:
  seed:
    values: [ 0, 1, 2, 3, 4 ]
  oracle:
    aug:
      values: [ 0.001, 0.005, 0.01, 0.02, 0.05 ]
    scale:
      values: [ 1, 10, 50, 100 ]
    lr_actor:
      values: [ 0.00085, 0.0008, 0.0007 ]
    lr_critic:
      values: [ 0.00085, 0.0008, 0.0007 ]
    hidden_size_actor:
      values: [ 64 ]
    hidden_size_critic:
      values: [ 128 ]
    num_hidden_layers_actor:
      values: [ 2 ]
    num_hidden_layers_critic:
      values: [ 2 ]
    max_grad_norm:
      values: [ 5, 10 ]
    v_coef:
      values: [ 0.3 ]
    e_coef:
      values: [ 0.001, 0.005 ]
    n_steps:
      values: [ 16 ]
    normalize_advantage:
      values: [ false ]
    pretraining_steps:
      values: [ 0 ]
    online_steps:
      values: [ 2.5e4 ]