name: a2c
method: grid
metric:
  name: outer/hypervolume
  goal: maximize
parameters:
  seed:
    values: [ 0, 1, 2, 3, 4 ]
  oracle:
    aug:
      values: [ 0.01, 0.1 ]
    scale:
      values: [ 50, 100 ]
    lr_actor:
      values: [ 0.0007, 0.0005, 0.0003, 0.0001 ]
    lr_critic:
      values: [ 0.0007, 0.0005, 0.0003, 0.0001 ]
    num_hidden_layers:
      values: [ 2 ]
    hidden_size:
      values: [ 256 ]
    num_referents:
        values: [ 16 ]
    max_grad_norm:
      values: [ -1, 0.5 ]
    v_coef:
        values: [ 0.5 ]
    e_coef:
        values: [ 0.01 ]
    normalize_advantage:
        values: [ False ]
    critic_activation:
        values: [ tanh ]
    actor_activation:
        values: [ tanh, relu ]
    pretraining_steps:
      values: [ 5000, 10000, 15000 ]
    online_steps:
      values: [ 5000, 10000, 15000 ]