name: dqn_no_pretrain_4
method: grid
metric:
  name: outer/hypervolume
  goal: maximize
parameters:
  seed:
    values: [ 0, 1, 2, 3, 4 ]
  oracle:
    aug:
      values: [ 0.001, 0.005, 0.01 ]
    lr:
      values: [ 0.00055, 0.000525, 0.0005, 0.000475, 0.00045 ]
    num_hidden_layers:
      values: [ 2 ]
    hidden_size:
      values: [ 128 ]
    activation:
      values: [ tanh ]
    pre_train_freq:
      values: [ 1 ]
    online_train_freq:
      values: [ 1 ]
    num_referents:
      values: [ 16 ]
    batch_size:
      values: [ 32 ]
    buffer_size:
      values: [ 2500 ]
    online_exploration_frac:
      values: [ 0.5 ]
    tau:
      values: [ 0.1 ]
    pretraining_steps:
      values: [ 0 ]
    online_steps:
      values: [ 2.5e4 ]