name: dqn_1
method: grid
metric:
  name: outer/hypervolume
  goal: maximize
parameters:
  seed:
    values: [ 0, 1, 2, 3, 4 ]
  oracle:
    lr:
      values: [ 0.001, 0.0009, 0.0008, 0.0007, 0.0006, 0.0005, 0.0003 ]
    num_hidden_layers:
      values: [ 1, 2 ]
    hidden_size:
      values: [ 128, 256 ]
    activation:
      values: [ tanh ]
    pre_train_freq:
      values: [ 4 ]
    num_referents:
      values: [ 16, 32 ]
    batch_size:
      values: [ 32, 64, 128 ]
    buffer_size:
      values: [ 2500, 5000, 10000 ]
    pretraining_steps:
      values: [ 5000 ]
    online_steps:
      values: [ 5000 ]