name: dqn_no_pretrain_1
method: bayes
metric:
  name: mean_hv
  goal: maximize
parameters:
  num_seeds:
    values: [ 5 ]
  oracle:
    aug:
      distribution: q_uniform
      min: 0.0001
      max: 1
      q: 0.0001
    scale:
      distribution: q_uniform
      min: 1
      max: 200
      q: 10
    lr:
      distribution: q_uniform
      min: 0.0001
      max: 0.001
      q: 0.0001
    num_hidden_layers:
      values: [ 2 ]
    hidden_size:
      values: [ 64, 128, 256 ]
    activation:
      values: [ relu, tanh ]
    pre_train_freq:
      values: [ 1, 2, 3 ]
    online_train_freq:
      values: [ 1, 2, 4 ]
    num_referents:
      values: [ 16 ]
    batch_size:
      values: [ 32, 64, 128 ]
    buffer_size:
      distribution: q_uniform
      min: 1000
      max: 30000
      q: 1000
    online_exploration_frac:
      values: [ 0.3, 0.5, 0.6 ]
    tau:
      distribution: q_uniform
      min: 0.1
      max: 1
      q: 0.1
    pretraining_steps:
      values: [ 0 ]
    online_steps:
      values: [ 2e4, 2.5e4, 3e4 ]