name: dqn_no_pretrain_1
method: grid
metric:
  name: outer/hypervolume
  goal: maximize
parameters:
  seed:
    values: [ 0, 1, 2, 3, 4 ]
  oracle:
    lr:
      values: [ 0.0006, 0.00055, 0.0005, 0.00045, 0.0004 ]
    num_hidden_layers:
      values: [ 2 ]
    hidden_size:
      values: [ 64, 128 ]
    activation:
      values: [ tanh ]
    pre_train_freq:
      values: [ 1 ]
    num_referents:
      values: [ 16 ]
    batch_size:
      values: [ 16, 32, 64 ]
    buffer_size:
      values: [ 2000, 2500, 3000 ]
    pretraining_steps:
      values: [ 0 ]
    online_steps:
      values: [ 1.5e4, 2e4, 2.5e4 ]