name: dqn_no_pretrain_2
method: grid
metric:
  name: outer/hypervolume
  goal: maximize
parameters:
  seed:
    values: [ 0, 1, 2, 3, 4 ]
  oracle:
    lr:
      values: [ 0.00055, 0.0005, 0.00045 ]
    num_hidden_layers:
      values: [ 2 ]
    hidden_size:
      values: [ 128 ]
    activation:
      values: [ tanh ]
    pre_train_freq:
      values: [ 1 ]
    num_referents:
      values: [ 16 ]
    batch_size:
      values: [ 32 ]
    buffer_size:
      values: [ 2500 ]
    pretraining_steps:
      values: [ 0 ]
    online_steps:
      values: [ 2.5e4 ]
    online_epsilon_start:
      values: [ 1.0 ]
    online_epsilon_end:
      values: [ 0.05, 0.1 ]
    online_exploration_frac:
      values: [ 0.3, 0.5, 0.7 ]