name: dqn_no_pretrain
method: grid
metric:
  name: score
  goal: maximize
parameters:
  num_seeds:
    values: [ 5 ]
  oracle:
    aug:
      values: [ 0.1, 0.2, 0.3, 0.4 ]
    scale:
      values: [ 100 ]
    optim_name:
      values: [ adamw ]
    lr:
      values: [ 0.0001, 0.00015, 0.0002, 0.00025, 0.0003, 0.00035 ]
    num_hidden_layers:
      values: [ 2 ]
    hidden_size:
      values: [ 128, 256 ]
    activation:
      values: [ tanh ]
    online_train_freq:
      values: [ 1, 2 ]
    num_referents:
      values: [ 16 ]
    batch_size:
      values: [ 512 ]
    buffer_size:
      values: [ 10000, 12500, 15000, 17500, 20000 ]
    clear_buffer:
      values: [ true ]
    online_exploration_frac:
      values: [ 0.7, 0.75, 0.8, 0.85 ]
    tau:
      values: [ 0.2, 0.25, 0.3, 0.35, 0.4 ]
    pretraining_steps:
      values: [ 0 ]
    online_steps:
      values: [ 2.5e4, 3e4 ]