name: dqn_no_pretrain_2
method: grid
metric:
  name: outer/hypervolume
  goal: maximize
parameters:
  seed:
    values: [ 0, 1, 2, 3, 4 ]
  oracle:
    lr:
      values: [ 0.001, 0.0009, 0.0007, 0.0005 ]
    num_hidden_layers:
      values: [ 1, 2 ]
    hidden_size:
      values: [ 64, 128, 256 ]
    activation:
      values: [ tanh ]
    pre_train_freq:
      values: [ 1, 2 ]
    num_referents:
      values: [ 16 ]
    batch_size:
      values: [ 32, 64, 128, 256 ]
    buffer_size:
      values: [ 2500, 3000, 5000 ]
    pretraining_steps:
      values: [ 0 ]
    online_steps:
      values: [ 1.5e4, 2e4, 2.5e4 ]