name: dqn_no_pretrain
method: grid
metric:
  name: score
  goal: maximize
parameters:
  num_seeds:
    values: [ 5 ]
  oracle:
    aug:
      values: [ 0.4 ]
    scale:
      values: [ 100 ]
    optim_name:
      values: [ adam, adamw ]
    lr:
      values: [ 0.0001, 0.00015, 0.0002, 0.00025, 0.0003, 0.00035, 0.0004 ]
    num_hidden_layers:
      values: [ 2, 3 ]
    hidden_size:
      values: [ 128, 256 ]
    activation:
      values: [ tanh ]
    online_train_freq:
      values: [ 1, 2 ]
    num_referents:
      values: [ 16 ]
    batch_size:
      values: [ 512, 1024 ]
    buffer_size:
      values: [ 15000, 20000, 25000 ]
    clear_buffer:
      values: [ true ]
    online_exploration_frac:
      values: [ 0.7, 0.75, 0.8 ]
    tau:
      values: [ 0.2, 0.25, 0.3, 0.35 ]
    pretraining_steps:
      values: [ 0 ]
    online_steps:
      values: [ 2.5e4 ]