name: dqn_no_pretrain
method: bayes
metric:
  name: score
  goal: maximize
parameters:
  num_seeds:
    values: [ 5 ]
  oracle:
    aug:
      distribution: q_uniform
      min: 0.01
      max: 0.5
      q: 0.01
    scale:
      values: [ 50, 100, 150 ]
    lr:
      distribution: q_uniform
      min: 0.0001
      max: 0.001
      q: 0.0001
    num_hidden_layers:
      values: [ 1, 2, 3 ]
    hidden_size:
      values: [ 64, 128, 256 ]
    activation:
      values: [ tanh ]
    online_train_freq:
      values: [ 1, 2 ]
    num_referents:
      values: [ 16 ]
    batch_size:
      values: [ 32, 64, 128, 256 ]
    buffer_size:
      distribution: q_uniform
      min: 5000
      max: 30000
      q: 2500
    clear_buffer:
      values: [ true, false ]
    online_exploration_frac:
      distribution: q_uniform
      min: 0.3
      max: 0.8
      q: 0.1
    tau:
      distribution: q_uniform
      min: 0.1
      max: 0.5
      q: 0.1
    pretraining_steps:
      values: [ 0 ]
    online_steps:
      distribution: q_uniform
      min: 2e4
      max: 4e4
      q: 1e3