name: dqn_large
method: grid
metric:
  name: outer/hypervolume
  goal: maximize
parameters:
  seed:
    values: [ 0, 1, 2, 3, 4 ]
  oracle:
    aug:
      values: [ 0.01, 0.1 ]
    scale:
      values: [ 50, 100 ]
    lr:
      values: [ 0.0007, 0.0006, 0.0005, 0.0004, 0.0003, 0.0002 ]
    num_hidden_layers:
      values: [ 3 ]
    hidden_size:
      values: [ 256 ]
    activation:
      values: [ tanh ]
    pre_train_freq:
      values: [ 4, 8 ]
    num_referents:
      values: [ 16, 32 ]
    batch_size:
      values: [ 32, 64, 128 ]
    buffer_size:
      values: [ 2500, 5000, 10000 ]
    pretraining_steps:
      values: [ 5000, 10000 ]
    online_steps:
      values: [ 5000, 10000 ]