name: ppo_8
method: grid
metric:
  name: outer/hypervolume
  goal: maximize
parameters:
  seed:
    values: [ 0, 1, 2, 3, 4 ]
  oracle:
    lr_actor:
      values: [ 0.0002, 0.0003, 0.0004, 0.0005, 0.0006, 0.0007 ]
    lr_critic:
      values: [ 0.0002, 0.0003, 0.0004, 0.0005, 0.0006, 0.0007 ]
    hidden_size_actor:
      values: [ 64, 128 ]
    hidden_size_critic:
      values: [ 64, 128 ]
    num_hidden_layers_actor:
        values: [ 1, 2 ]
    num_hidden_layers_critic:
        values: [ 1, 2 ]
    max_grad_norm:
      values: [ 0.5, 1, 5 ]