name: ppo_no_pretrain_1
method: grid
metric:
  name: outer/hypervolume
  goal: maximize
parameters:
  seed:
    values: [ 0, 1, 2, 3, 4 ]
  oracle:
    lr_actor:
      values: [ 0.0009, 0.0007, 0.0005, 0.0003 ]
    lr_critic:
      values: [ 0.0009, 0.0007, 0.0005, 0.0003 ]
    hidden_size_actor:
      values: [ 64, 128 ]
    hidden_size_critic:
      values: [ 64, 128 ]
    num_hidden_layers_actor:
      values: [ 1, 2 ]
    num_hidden_layers_critic:
      values: [ 1, 2 ]
    max_grad_norm:
      values: [ 0.5, 1, 5 ]
    n_steps:
      values: [ 8, 16 ]
    normalize_advantage:
      values: [ true, false ]
    pretraining_steps:
      values: [ 0 ]
    online_steps:
      values: [ 1e4, 2e4 ]