# Experiment params
env_id: deep-sea-treasure-concave-v0
max_episode_steps: 50
one_hot_wrapper: True
gamma: 1.0
study_name: sn_a2c_dst
seed: 1
wandb_project_name: IPRO_dst_neurips
wandb_entity: null
n_trials: 1


# Outer loop params
outer_loop:
  method: IPRO-2D
  tolerance: 0.0
  max_iterations: null
  track: True


# Oracle params
oracle:
  algorithm: SN-MO-A2C
  aug: 0.01
  scale: 100
  grid_sample: True
  actor_activation: relu
  critic_activation: relu
  pretrain_iters: 30
  num_referents: 4
  v_coef: 0.5
  e_coef: 0.01
  normalize_advantage: True
  gae_lambda: 0.95
  max_grad_norm: 0.5
  eval_episodes: 1
  n_steps: 8
  log_freq: 1000
  track: False


# Hyperparameter options to be selected during the optimisation
hyperparameters:
  lr_actor:
    type: categorical
    choices: [ 0.0007, 0.0006, 0.0005, 0.0004, 0.0003, 0.0002, 0.0001 ]
  lr_critic:
    type: categorical
    choices: [ 0.0007, 0.0006, 0.0005, 0.0004, 0.0003, 0.0002, 0.0001 ]
  num_hidden_layers:
    type: categorical
    choices: [ 2, 3 ]
  hidden_size:
    type: categorical
    choices: [ 128, 256 ]
  pretraining_steps:
    type: categorical
    choices: [ 10000, 20000, 30000 ]
  online_steps:
    type: categorical
    choices: [ 5000, 10000 ]
