# Experiment params
env_id: minecart-v0
max_episode_steps: 1000
one_hot_wrapper: False
gamma: 0.98
study_name: sn_a2c_minecart
seed: 1
wandb_project_name: IPRO_minecart_neurips
wandb_entity: null
n_trials: 1


# Outer loop params
outer_loop:
  method: IPRO
  tolerance: 1.e-15
  max_iterations: 200
  track: True


# Oracle params
oracle:
  algorithm: SN-MO-A2C
  aug: 0.01
  scale: 100
  grid_sample: True
  pretrain_iters: 25
  normalize_advantage: True
  v_coef: 0.5
  e_coef: 0.01
  num_referents: 4
  gae_lambda: 0.95
  max_grad_norm: 0.5
  n_steps: 128
  eval_episodes: 100
  log_freq: 1000
  track: False


# Hyperparameter options to be selected during the optimisation
hyperparameters:
  lr_actor:
    type: categorical
    choices: [ 0.0007, 0.0005, 0.0004, 0.0003, 0.0002, 0.0001 ]
  lr_critic:
    type: categorical
    choices: [ 0.0007, 0.0005, 0.0004, 0.0003, 0.0002, 0.0001 ]
  hidden_size_actor:
    type: categorical
    choices: [ 128, 256 ]
  hidden_size_critic:
    type: categorical
    choices: [ 128, 256 ]
  num_hidden_layers_actor:
    type: categorical
    choices: [ 2, 3, 4 ]
  num_hidden_layers_critic:
    type: categorical
    choices: [ 2, 3, 4 ]
  pretraining_steps:
    type: categorical
    choices: [ 35000, 50000 ]
  online_steps:
    type: categorical
    choices: [ 25000, 30000 ]
