# Experiment params
env_id: deep-sea-treasure-concave-v0
max_episode_steps: 50
one_hot_wrapper: True
gamma: 1.0
study_name: sn_dqn_dst
seed: 1
wandb_project_name: IPRO_dst_neurips
wandb_entity: null
n_trials: 1


# Outer loop params
outer_loop:
  method: IPRO-2D
  tolerance: 0.0
  max_iterations: null
  track: True


# Oracle params
oracle:
  algorithm: SN-MO-DQN
  aug: 0.01
  scale: 100
  grid_sample: True
  pretrain_iters: 25
  online_train_freq: 10
  pre_train_freq: 10
  target_update_freq: 1
  gradient_steps: 1
  pre_learning_start: 100
  pre_epsilon_start: 1.0
  pre_epsilon_end: 0.05
  pre_exploration_frac: 0.5
  online_learning_start: 100
  online_epsilon_start: 1.0
  online_epsilon_end: 0.05
  online_exploration_frac: 0.3
  buffer_size: 100000
  batch_size: 128
  tau: 0.1
  num_referents: 4
  eval_episodes: 1
  log_freq: 500
  track: False


# Hyperparameter options to be selected during the optimisation
hyperparameters:
  lr:
    type: categorical
    choices: [ 0.00075, 0.0007, 0.00065, 0.0006, 0.0005, 0.0003, 0.00025 ]
  activation:
    type: categorical
    choices: [ relu, tanh ]
  num_hidden_layers:
    type: categorical
    choices: [ 2, 3 ]
  hidden_size:
    type: categorical
    choices: [ 128, 256 ]
  online_steps:
    type: categorical
    choices: [ 5000, 10000 ]
  pretraining_steps:
    type: categorical
    choices: [ 2500, 5000 ]