# Experiment params
env_id: mo-walker2d-v4
max_episode_steps: 100
one_hot_wrapper: False
gamma: 1.0
study_name: sn_ddpg_dst
seed: 1
wandb_project_name: IPRO_walker
wandb_entity: null
n_trials: 1


# Outer loop params
outer_loop:
  method: IPRO-2D
  tolerance: 0.0
  max_iterations: null
  track: True


# Oracle params
oracle:
  algorithm: SN-MO-DDPG
  aug: 0.01
  scale: 100
  actor_activation: relu
  critic_activation: relu
  pretrain_iters: 50
  grid_sample: True
  online_train_freq: 1
  pre_train_freq: 1
  target_update_freq: 1
  gradient_steps: 1
  pre_learning_start: 100
  pre_epsilon_start: 1.0
  pre_epsilon_end: 0.05
  pre_exploration_frac: 0.5
  online_learning_start: 100
  online_epsilon_start: 1.0
  online_epsilon_end: 0.05
  online_exploration_frac: 0.3
  buffer_size: 10000
  tau: 0.1
  num_referents: 4
  eval_episodes: 1
  log_freq: 500
  track: False


# Hyperparameter options to be selected during the optimisation
hyperparameters:
  lr_actor:
    type: categorical
    choices: [ 0.001, 0.0007, 0.0003, 0.0001 ]
  lr_critic:
    type: categorical
    choices: [ 0.001, 0.0007, 0.0003, 0.0001 ]
  hidden_size_actor:
    type: categorical
    choices: [ 64, 128, 256 ]
  hidden_size_critic:
    type: categorical
    choices: [ 64, 128, 256 ]
  num_hidden_layers_actor:
    type: int
    min: 1
    max: 4
  num_hidden_layers_critic:
    type: int
    min: 1
    max: 4
  batch_size:
    type: categorical
    choices: [ 32, 64 ]
  online_steps:
    type: categorical
    choices: [ 5000, 6000, 7500 ]
  pretraining_steps:
    type: categorical
    choices: [ 5000, 6000, 7500 ]