# Experiment params
env_id: minecart-v0
max_episode_steps: 1000
one_hot_wrapper: False
gamma: 0.98
study_name: sn_dqn_minecart
seed: 1
wandb_project_name: IPRO_minecart_neurips
wandb_entity: null
n_trials: 1


# Outer loop params
outer_loop:
  method: IPRO
  tolerance: 1.e-15
  max_iterations: 5000
  track: True


# Oracle params
oracle:
  algorithm: SN-MO-DQN
  aug: 0.01
  scale: 100
  grid_sample: True
  activation: relu
  pretrain_iters: 25
  pre_train_freq: 10
  online_train_freq: 10
  target_update_freq: 1
  gradient_steps: 1
  pre_learning_start: 100
  pre_epsilon_start: 1.0
  pre_epsilon_end: 0.05
  pre_exploration_frac: 0.5
  online_learning_start: 100
  online_epsilon_start: 1.0
  online_epsilon_end: 0.05
  online_exploration_frac: 0.3
  tau: 0.1
  buffer_size: 1000000
  batch_size: 128
  num_referents: 4
  eval_episodes: 100
  log_freq: 500
  track: False


# Hyperparameter options to be selected during the optimisation
hyperparameters:
  lr:
    type: categorical
    choices: [ 0.0007, 0.0006, 0.0005, 0.0004, 0.0003 ]
  num_hidden_layers:
    type: categorical
    choices: [ 2, 3, 4 ]
  hidden_size:
    type: categorical
    choices: [ 128, 256 ]
  pretraining_steps:
    type: categorical
    choices: [ 25000, 50000 ]
  online_steps:
    type: categorical
    choices: [ 15000, 20000 ]
