# Experiment params
env_id: deep-sea-treasure-concave-v0
max_episode_steps: 50
one_hot_wrapper: True
gamma: 1.0
study_name: sn_ppo_dst
seeds: [0, 1, 2, 3, 4]
wandb_project_name: IPRO_dst_neurips_ai
wandb_entity: null
n_trials: 1


# Outer loop params
outer_loop:
  method: IPRO-2D
  tolerance: 0.0
  max_iterations: null
  track: True


# Oracle params
oracle:
  algorithm: SN-MO-PPO
  aug: 0.01
  scale: 100
  grid_sample: True
  critic_activation: tanh
  pretrain_iters: 30
  v_coef: 0.5
  e_coef: 0.01
  eps: 1.e-5
  anneal_lr: False
  num_minibatches: 4
  normalize_advantage: True
  gae_lambda: 0.95
  clip_coef: 0.2
  clip_range_vf: 0.2
  num_envs: 8
  n_steps: 8
  num_referents: 4
  update_epochs: 4
  max_grad_norm: 0.5
  target_kl: None
  eval_episodes: 1
  log_freq: 1000
  track: False


# Hyperparameter options to be selected during the optimisation
hyperparameters:
  lr_actor:
    type: categorical
    choices: [ 0.0006, 0.0005, 0.0004, 0.0003 ]
  lr_critic:
    type: categorical
    choices: [ 0.0006, 0.0005, 0.0004, 0.0003 ]
  num_hidden_layers:
    type: categorical
    choices: [ 1, 2 ]
  hidden_size:
    type: categorical
    choices: [ 128, 256 ]
  actor_activation:
    type: categorical
    choices: [ tanh, relu ]
  pretraining_steps:
    type: categorical
    choices: [ 15000 ]
  online_steps:
    type: categorical
    choices: [ 5000 ]
