# Experiment params
env_id: deep-sea-treasure-concave-v0
max_episode_steps: 50
one_hot_wrapper: True
gamma: 1.0
study_name: a2c_dst
seed: 1
wandb_project_name: IPRO_test
wandb_entity: null
n_trials: 1


# Outer loop params
outer_loop:
  method: IPRO
  tolerance: 0.0
  max_iterations: 2
  track: False


# Oracle params
oracle:
  algorithm: MO-A2C
  warm_start: False
  eval_episodes: 1
  log_freq: 500
  track: False


# Hyperparameter options to be selected during the optimisation
hyperparameters:
  aug:
    type: categorical
    choices: [ 0, 0.001, 0.005, 0.01, 0.1 ]
  scale:
    type: categorical
    choices: [ 1, 10, 100, 500, 1000 ]
  global_steps:
    type: constant
    value: 10000
  num_hidden_layers:
    type: int
    min: 1
    max: 3
  hidden_size:
    type: categorical
    choices: [ 32, 64, 128, 256 ]
  lr_actor:
    type: categorical
    choices: [ 1.e-4, 3.e-4, 5.e-4, 1.e-3 ]
  lr_critic:
    type: categorical
    choices: [ 1.e-4, 3.e-4, 5.e-4, 1.e-3 ]
  e_coef:
    type: categorical
    choices: [ 0.001, 0.005, 0.01, 0.05, 0.1 ]
  v_coef:
    type: categorical
    choices: [ 0.1, 0.5, 1.0 ]
  max_grad_norm:
    type: categorical
    choices: [ 0.5, 1.0, 5.0, 10.0, 50.0 ]
  normalize_advantage:
    type: categorical
    choices: [ True, False ]
  n_steps:
    type: categorical
    choices: [ 32, 64, 128 ]
  gae_lambda:
    type: categorical
    choices: [ 0.5, 0.95, 0.99, 1. ]
