algorithm: SN-MO-A2C
aug: 0.01
scale: 100
lr_actor: 3e-4
lr_critic: 3e-4
actor_hidden: [ 64, 64 ]
critic_hidden: [ 64, 64 ]
actor_activation: tanh
critic_activation: tanh
v_coef: 0.5
e_coef: 0.01
max_grad_norm: 0.5
normalize_advantage: false
n_steps: 16
gae_lambda: 0.95
pretrain_iters: 50
grid_sample: true
num_referents: 16
pretraining_steps: 1e2
online_steps: 7.5e4