algorithm: SN-MO-A2C
aug: 0.01
scale: 100
grid_sample: True
pretrain_iters: 30
num_referents: 16
critic_activation: tanh
actor_activation: tanh
v_coef: 0.5
e_coef: 0.01
normalize_advantage: False
gae_lambda: 0.95
n_steps: 16
eval_episodes: 100
log_freq: 1000
track: False