algorithm: SN-MO-DQN
aug: 0.01
scale: 100
grid_sample: True
pretrain_iters: 30
activation: tanh
pre_train_freq: 4
online_train_freq: ${.pre_train_freq}
target_update_freq: 1
gradient_steps: 1
pre_learning_start: 100
pre_epsilon_start: 1.0
pre_epsilon_end: 0.05
pre_exploration_frac: 0.5
online_learning_start: 100
online_epsilon_start: 1.0
online_epsilon_end: 0.05
online_exploration_frac: 0.5
batch_size: 64
buffer_size: 10000
tau: 0.1
eval_episodes: 1
log_freq: 500
track: False