algorithm: SN-MO-DQN
aug: 0.01
scale: 100
lr: 3e-4
hidden_layers: [ 64, 64 ]
activation: tanh
pre_train_freq: 4
online_train_freq: ${.pre_train_freq}
target_update_freq: 1
gradient_steps: 1
pretrain_iters: 50
grid_sample: True
num_referents: 16
pre_learning_start: 100
pre_epsilon_start: 1.0
pre_epsilon_end: 0.05
pre_exploration_frac: 0.5
pretraining_steps: 1e5
online_learning_start: 100
online_epsilon_start: 1.0
online_epsilon_end: 0.05
online_exploration_frac: 0.5
online_steps: 1e5
tau: 0.1
buffer_size: 1e4
batch_size: 64
clear_buffer: False