algorithm: SN-MO-PPO
aug: 0.01
scale: 100
grid_sample: True
pretrain_iters: 30
critic_activation: tanh
actor_activation: tanh
v_coef: 0.5
e_coef: 0.01
eps: 1.e-5
anneal_lr: False
num_minibatches: 4
normalize_advantage: False
gae_lambda: 0.95
clip_coef: 0.2
clip_range_vf: 0.2
num_envs: 8
num_referents: 16
n_steps: 16
update_epochs: 4
max_grad_norm: 0.5
target_kl: None
eval_episodes: 100
log_freq: 1000
track: False